### DISCUSSION TITLE
چطور میتونم چند تقویم با تنظیمات مختلف داشته باشم؟

### DISCUSSION THREAD

**Discussion by fariborzj2** [majidh1/JalaliDatePicker#44] [Question] [answered]
سلام 
چطور میتونم چند تقویم با تنظیمات مختلف داشته باشم؟
و اینکه چطور dropdown روی برای ماه غیر فعال کنیم؟

**Comment by majidh1** [comment, marked as answer]
سلام 
شما میتونید چند تقویم با تنظیمات مختلف داشته باشید. نمونه زیر این کار رو انجام داده
https://codepen.io/majidh1/pen/rNKYPqG

غیر فعال کردن دراپ دان ماه با css امکان پذیر هست ولی اگه نیاز شما این هست که ماه تغییر نکنه میتونید به وسیله اتریبیوت محدودیت تاریخ اعمال کنید.

css:
```css
jdp-container .jdp-month select {
    pointer-events: none;
    touch-action: none;
    appearance: none;
}
```
