### DISCUSSION TITLE
چطور ظاهر تقویم را به شکل یکی از اسکرین شات های ارائه شده تغییر دهیم؟

### DISCUSSION THREAD

**Discussion by danialranjbar** [majidh1/JalaliDatePicker#64] [Question] [answered]
عرض سلام و احتراما
اولا چطور هدر تقویم رو مثل اسکرین شاتی که خودتون گرفتید آبی کنیم؟
دوما مثلا فرض بفرمایید بخایم اصلا بادمچونی کنیم چکار کنیم آیا بریم تو فایل sass دستکاری کنیم یا خودتون یکسری pre-set ارائه کردید و بنده خبر ندارم؟
با تشکر از زحماتی که برای این پروژه کشیدید

**Comment by majidh1** [comment, marked as answer]
سلام مرسی از پیامتون
شما میتوانید از دو پارامتر
plusHtml و minusHtml
جهت تغییر ایکون ها استفاده کنید

 برای تغییرات یو آی میتوانید از سی اس اس استفاده کنید
به دلیل ثابت بودن کلاس های دیتپیکر استفاده از سی اس اس بدون مشکل هست
اینم نمونه که یکی از دوستان استفاده کرده در پروژه خودش:

<img src="/majidh1/JalaliDatePicker/raw/main/res/sample5.png" width="32%" style="max-width:100%;">

```css
jdp-container,jdp-container .jdp-year select,jdp-container .jdp-month select{
    background: #323232;
}

jdp-container .jdp-months, jdp-container .jdp-years {
    color: rgb(255 255 255 / 80%);
    fill: rgb(255 255 255 / 80%);
}
jdp-container .jdp-day-name {
    background-color: rgb(255 255 255 / 10%);
}
jdp-container .jdp-day, jdp-container .jdp-day-name {
    color: rgb(255 255 255 / 80%);
}
jdp-container .jdp-day:empty {
    border-color: #323232;
}
jdp-container .jdp-btn-empty, jdp-container .jdp-btn-today, jdp-container .jdp-days .jdp-day.selected {
    background: #1d497e !important;
}
```
