### DISCUSSION TITLE
چطور کاری کنیم تا تقویم وسط در وسط صفحه اصلی سایتمون باز بشه؟

### DISCUSSION THREAD

**Discussion by danialranjbar** [majidh1/JalaliDatePicker#65] [Question] [answered]
ایا این مسیر 
position absolute
top -50%
left -50%
transform translate 50% 50%
 رو بریم یا راه حل بهتری خودتون ارائه دادید؟
 با تشکر از زحماتتون

**Comment by majidh1** [comment, marked as answer]
سلام ممنون از مشارکت شما
میتونید از این کد استفاده کنید:

```css
jdp-overlay{
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background-color: rgba(0,0,0,0.3);
        backdrop-filter: blur(2px);
        -webkit-backdrop-filter: blur(2px);
        display: none;
}
jdp-container{
    top: 50% !important;
    left: 50% !important;
    bottom: unset !important;
    right: unset !important;
    transform: translate(-50%,-50%) !important;
}
```
